export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const CHANGE_SELECT = 'CHANGE_SELECT'
export const CHANGE_NAV = 'CHANGE_NAV'
export const GET_F6_DATA = 'GET_F6_DATA'
export const GET_F7_DATA = 'GET_F7_DATA'